// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdW_DhobJYL01QN-Q3CDPNznaMPUUJIew',
    appId: '1:395189673398:web:250c40414c724b29757517',
    messagingSenderId: '395189673398',
    projectId: 'ifeclickgame',
    authDomain: 'ifeclickgame.firebaseapp.com',
    storageBucket: 'ifeclickgame.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZy55x2vh31OHK8HYfs-Gz3iFPsdicqV8',
    appId: '1:395189673398:android:aea796df8f777943757517',
    messagingSenderId: '395189673398',
    projectId: 'ifeclickgame',
    storageBucket: 'ifeclickgame.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnIh20MBSU_ZzKKyLHvu5ePxFtp6-_CCQ',
    appId: '1:395189673398:ios:9895636df92d0e1f757517',
    messagingSenderId: '395189673398',
    projectId: 'ifeclickgame',
    storageBucket: 'ifeclickgame.appspot.com',
    iosBundleId: 'com.example.clickGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnIh20MBSU_ZzKKyLHvu5ePxFtp6-_CCQ',
    appId: '1:395189673398:ios:a5c303871899af0e757517',
    messagingSenderId: '395189673398',
    projectId: 'ifeclickgame',
    storageBucket: 'ifeclickgame.appspot.com',
    iosBundleId: 'com.example.clickGame.RunnerTests',
  );
}
